package telas;

import java.sql.*;
import javax.swing.JOptionPane;

public class TelaMenu extends javax.swing.JFrame {

    public TelaMenu() {
        initComponents();
    }

    public TelaMenu(String usuario, String cargo) {
        initComponents();
        pnlCadastrarProdutos.setVisible(false);
        lblSaldacao.setText("Bem vindo! " + usuario);
        if (cargo.equalsIgnoreCase("gerente")) {

        } else if (cargo.equalsIgnoreCase("caixa")) {
            chavear();

        } else if (cargo.equalsIgnoreCase("balconista")) {
            chavear();

        }

    }

    private void chavear() {
        itmCadastrarProdutos.setEnabled(false);
        itmAlterarProdutos.setEnabled(false);
        itmExcluirProdutos.setEnabled(false);
        itmRelatorioProdutos.setEnabled(true);
        itmCadastrarFuncionarios.setEnabled(false);
        itmAlterarFuncionarios.setEnabled(false);
        itmExcluirFuncionarios.setEnabled(false);
        itmRelatorioFuncionarios.setEnabled(false);

    }

    public TelaMenu(String cargo) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastrarProdutos = new javax.swing.JPanel();
        lblMarcaCadastrarProdutos = new javax.swing.JLabel();
        lblCodigoCadastrarProdutos = new javax.swing.JLabel();
        lblPrecoCadastrarProdutos = new javax.swing.JLabel();
        lblNomeCadastrarProdutos = new javax.swing.JLabel();
        txtPrecoCadastrarProdutos = new javax.swing.JTextField();
        txtCodigoCadastrarProdutos = new javax.swing.JTextField();
        txtNomeCadastrarProdutos = new javax.swing.JTextField();
        txtCategoriaCadastrarProdutos = new javax.swing.JTextField();
        btnSalvarCadastrarProduto = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnOutrosRelatorios = new javax.swing.JButton();
        lblSaldacao = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        mmuBar = new javax.swing.JMenuBar();
        mmuProdutos = new javax.swing.JMenu();
        itmCadastrarProdutos = new javax.swing.JMenuItem();
        itmAlterarProdutos = new javax.swing.JMenuItem();
        itmExcluirProdutos = new javax.swing.JMenuItem();
        itmRelatorioProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mmuFuncionarios = new javax.swing.JMenu();
        itmCadastrarFuncionarios = new javax.swing.JMenuItem();
        itmAlterarFuncionarios = new javax.swing.JMenuItem();
        itmExcluirFuncionarios = new javax.swing.JMenuItem();
        itmRelatorioFuncionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlCadastrarProdutos.setLayout(null);

        lblMarcaCadastrarProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMarcaCadastrarProdutos.setText("categoria:");
        pnlCadastrarProdutos.add(lblMarcaCadastrarProdutos);
        lblMarcaCadastrarProdutos.setBounds(30, 180, 80, 30);

        lblCodigoCadastrarProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCodigoCadastrarProdutos.setText("Código: ");
        pnlCadastrarProdutos.add(lblCodigoCadastrarProdutos);
        lblCodigoCadastrarProdutos.setBounds(30, 60, 80, 30);

        lblPrecoCadastrarProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecoCadastrarProdutos.setText("Preço: ");
        pnlCadastrarProdutos.add(lblPrecoCadastrarProdutos);
        lblPrecoCadastrarProdutos.setBounds(30, 240, 80, 30);

        lblNomeCadastrarProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeCadastrarProdutos.setText("Nome: ");
        pnlCadastrarProdutos.add(lblNomeCadastrarProdutos);
        lblNomeCadastrarProdutos.setBounds(30, 120, 80, 30);

        txtPrecoCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoCadastrarProdutosActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(txtPrecoCadastrarProdutos);
        txtPrecoCadastrarProdutos.setBounds(130, 240, 220, 30);

        txtCodigoCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCadastrarProdutosActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(txtCodigoCadastrarProdutos);
        txtCodigoCadastrarProdutos.setBounds(130, 60, 220, 30);

        txtNomeCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadastrarProdutosActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(txtNomeCadastrarProdutos);
        txtNomeCadastrarProdutos.setBounds(130, 120, 220, 30);

        txtCategoriaCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaCadastrarProdutosActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(txtCategoriaCadastrarProdutos);
        txtCategoriaCadastrarProdutos.setBounds(130, 180, 220, 30);

        btnSalvarCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvarCadastrarProduto.setText("Salvar");
        btnSalvarCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastrarProdutoActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnSalvarCadastrarProduto);
        btnSalvarCadastrarProduto.setBounds(30, 320, 120, 40);

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnConsultar);
        btnConsultar.setBounds(30, 320, 120, 40);

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnExcluir);
        btnExcluir.setBounds(200, 320, 120, 40);

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnAlterar);
        btnAlterar.setBounds(340, 320, 120, 40);

        btnOutrosRelatorios.setText("Outros Relatorios");
        btnOutrosRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutrosRelatoriosActionPerformed(evt);
            }
        });
        pnlCadastrarProdutos.add(btnOutrosRelatorios);
        btnOutrosRelatorios.setBounds(380, 60, 140, 40);

        getContentPane().add(pnlCadastrarProdutos);
        pnlCadastrarProdutos.setBounds(0, 30, 750, 450);

        lblSaldacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblSaldacao);
        lblSaldacao.setBounds(370, 40, 310, 40);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/New Project.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 100, 850, 440);

        mmuProdutos.setMnemonic('P');
        mmuProdutos.setText("Produtos");
        mmuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmuProdutosActionPerformed(evt);
            }
        });

        itmCadastrarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarProdutos.setText("Cadastrar");
        itmCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarProdutosActionPerformed(evt);
            }
        });
        mmuProdutos.add(itmCadastrarProdutos);

        itmAlterarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAlterarProdutos.setText("Alterar");
        itmAlterarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarProdutosActionPerformed(evt);
            }
        });
        mmuProdutos.add(itmAlterarProdutos);

        itmExcluirProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExcluirProdutos.setText("Excluir");
        itmExcluirProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirProdutosActionPerformed(evt);
            }
        });
        mmuProdutos.add(itmExcluirProdutos);

        itmRelatorioProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmRelatorioProdutos.setText("Relatórios");
        itmRelatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRelatorioProdutosActionPerformed(evt);
            }
        });
        mmuProdutos.add(itmRelatorioProdutos);

        mmuBar.add(mmuProdutos);
        mmuBar.add(jMenu2);

        mmuFuncionarios.setMnemonic('F');
        mmuFuncionarios.setText("Funcionários");

        itmCadastrarFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarFuncionarios.setText("Cadastrar");
        mmuFuncionarios.add(itmCadastrarFuncionarios);

        itmAlterarFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAlterarFuncionarios.setText("Alterar");
        itmAlterarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFuncionariosActionPerformed(evt);
            }
        });
        mmuFuncionarios.add(itmAlterarFuncionarios);

        itmExcluirFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExcluirFuncionarios.setText("Excluir");
        mmuFuncionarios.add(itmExcluirFuncionarios);

        itmRelatorioFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmRelatorioFuncionarios.setText("Relatórios");
        mmuFuncionarios.add(itmRelatorioFuncionarios);

        mmuBar.add(mmuFuncionarios);

        setJMenuBar(mmuBar);

        setSize(new java.awt.Dimension(864, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mmuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmuProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmuProdutosActionPerformed

    private void itmCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarProdutosActionPerformed
        pnlCadastrarProdutos.setVisible(true);
        btnConsultar.setVisible(false);
        btnSalvarCadastrarProduto.setVisible(true);
        btnExcluir.setVisible(false);
        btnOutrosRelatorios.setVisible(false);
        btnAlterar.setVisible(false);


    }//GEN-LAST:event_itmCadastrarProdutosActionPerformed

    private void itmAlterarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarProdutosActionPerformed
        pnlCadastrarProdutos.setVisible(true);
        btnSalvarCadastrarProduto.setVisible(false);
        btnConsultar.setVisible(true);
        btnAlterar.setVisible(false);
        btnExcluir.setVisible(false);
        btnOutrosRelatorios.setVisible(false);
    }//GEN-LAST:event_itmAlterarProdutosActionPerformed

    private void itmAlterarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterarFuncionariosActionPerformed

    private void txtPrecoCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoCadastrarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoCadastrarProdutosActionPerformed

    private void txtCodigoCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCadastrarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCadastrarProdutosActionPerformed

    private void txtNomeCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadastrarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadastrarProdutosActionPerformed

    private void txtCategoriaCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaCadastrarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaCadastrarProdutosActionPerformed

    private void btnSalvarCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastrarProdutoActionPerformed
        try {
            Connection conexao;
            PreparedStatement cdp;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/bancopadaria", "root", "admin123");

            cdp = conexao.prepareStatement("INSERT INTO cadastrar_produtos VALUES(?, ?, ?, ?)");
            cdp.setString(1, txtCodigoCadastrarProdutos.getText());            // 1  2  3  4  
            cdp.setString(2, txtNomeCadastrarProdutos.getText());
            cdp.setString(3, txtCategoriaCadastrarProdutos.getText());
            cdp.setDouble(4, Double.parseDouble(txtPrecoCadastrarProdutos.getText()));

            cdp.executeUpdate(); //Executa o comando INSERT
            JOptionPane.showMessageDialog(btnSalvarCadastrarProduto, "Dados salvos com sucesso");

            txtCodigoCadastrarProdutos.setText("");
            txtNomeCadastrarProdutos.setText("");
            txtCategoriaCadastrarProdutos.setText("");
            txtPrecoCadastrarProdutos.setText("");
            txtCodigoCadastrarProdutos.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro " + ex.getMessage() + "\nEntre em contato com o administrador e informe o número do erro");
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(null, "Algum parametro do BD esta incorreto" + ex.getErrorCode());
                txtCodigoCadastrarProdutos.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "erro número " + ex.getErrorCode() + "\nEntre em contato com o administrador e informe o número do erro");
            }
        }


    }//GEN-LAST:event_btnSalvarCadastrarProdutoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (txtCodigoCadastrarProdutos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o código do produto");
            txtCodigoCadastrarProdutos.requestFocus();
            return; // para a execução nesta linha (stop)       
        }
        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;
            //Conexão com o BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancopadaria", "root", "admin123");
            //Busca o produto na tabela produtos do BD
            st = conexao.prepareStatement("SELECT * FROM cadastrar_produtos WHERE codigo=?");
            st.setString(1, txtCodigoCadastrarProdutos.getText());
            resultado = st.executeQuery(); //Executa o SELECT criado acima
            if (resultado.next()) { // Se encontrou o código do produto na tabela
                txtNomeCadastrarProdutos.setText(resultado.getString("nome"));
                txtCategoriaCadastrarProdutos.setText(resultado.getString("categoria"));
                txtPrecoCadastrarProdutos.setText(resultado.getString("preço"));
                btnExcluir.setVisible(true);
                btnAlterar.setVisible(true);
            } else { //Senão encontrou o produto
                JOptionPane.showMessageDialog(null, "Produto n”ao encontrado");
                txtCodigoCadastrarProdutos.requestFocus();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void itmRelatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRelatorioProdutosActionPerformed
        pnlCadastrarProdutos.setVisible(true);
        btnSalvarCadastrarProduto.setVisible(false);
        btnConsultar.setVisible(true);
        btnExcluir.setVisible(false);
        btnOutrosRelatorios.setVisible(true);
        btnAlterar.setVisible(false);


    }//GEN-LAST:event_itmRelatorioProdutosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtCodigoCadastrarProdutos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o código do produto");
            txtCodigoCadastrarProdutos.requestFocus();
            return; // para a execução nesta linha (stop)       
        }
        try {
            Connection conexao;
            PreparedStatement st;
            //Conexão com o BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancopadaria", "root", "admin123");
            //Busca o produto na tabela produtos do BD
            st = conexao.prepareStatement("DELETE FROM cadastrar_produtos WHERE codigo=?");
            st.setString(1, txtCodigoCadastrarProdutos.getText());
            int res = st.executeUpdate();
            if (res == 1) {
                JOptionPane.showMessageDialog(null, "Produto excluido com sucesso");
                txtCodigoCadastrarProdutos.setText("");
                txtNomeCadastrarProdutos.setText("");
                txtCategoriaCadastrarProdutos.setText("");
                txtPrecoCadastrarProdutos.setText("");
                txtCodigoCadastrarProdutos.requestFocus();
                btnExcluir.setVisible(false);
                btnAlterar.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Não possível excluir o Produto excluido");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void itmExcluirProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirProdutosActionPerformed
        pnlCadastrarProdutos.setVisible(true);
        btnSalvarCadastrarProduto.setVisible(false);
        btnConsultar.setVisible(true);
        btnAlterar.setVisible(false);
        btnExcluir.setVisible(false);
        btnOutrosRelatorios.setVisible(false);


    }//GEN-LAST:event_itmExcluirProdutosActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancopadaria", "root", "admin123");
            st = conexao.prepareStatement("UPDATE cadastrar_produtos SET nome = ?, categoria = ?, preço = ? WHERE codigo = ?");
            st.setString(1, txtNomeCadastrarProdutos.getText());
            st.setString(2, txtCategoriaCadastrarProdutos.getText());
            st.setString(3, txtPrecoCadastrarProdutos.getText());
            st.setString(4, txtCodigoCadastrarProdutos.getText());
            st.executeUpdate(); //Executa o comando SQL UPDATE
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");
            txtCodigoCadastrarProdutos.setText("");
            txtNomeCadastrarProdutos.setText("");
            txtCategoriaCadastrarProdutos.setText("");
            txtPrecoCadastrarProdutos.setText("");
            txtCodigoCadastrarProdutos.requestFocus();
            btnExcluir.setVisible(false);
            btnAlterar.setVisible(false);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnOutrosRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutrosRelatoriosActionPerformed
        TelaRelatorios tela;
        tela = new TelaRelatorios();
        tela.setVisible(true);


    }//GEN-LAST:event_btnOutrosRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOutrosRelatorios;
    private javax.swing.JButton btnSalvarCadastrarProduto;
    private javax.swing.JMenuItem itmAlterarFuncionarios;
    private javax.swing.JMenuItem itmAlterarProdutos;
    private javax.swing.JMenuItem itmCadastrarFuncionarios;
    private javax.swing.JMenuItem itmCadastrarProdutos;
    private javax.swing.JMenuItem itmExcluirFuncionarios;
    private javax.swing.JMenuItem itmExcluirProdutos;
    private javax.swing.JMenuItem itmRelatorioFuncionarios;
    private javax.swing.JMenuItem itmRelatorioProdutos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lblCodigoCadastrarProdutos;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblMarcaCadastrarProdutos;
    private javax.swing.JLabel lblNomeCadastrarProdutos;
    private javax.swing.JLabel lblPrecoCadastrarProdutos;
    private javax.swing.JLabel lblSaldacao;
    private javax.swing.JMenuBar mmuBar;
    private javax.swing.JMenu mmuFuncionarios;
    private javax.swing.JMenu mmuProdutos;
    private javax.swing.JPanel pnlCadastrarProdutos;
    private javax.swing.JTextField txtCategoriaCadastrarProdutos;
    private javax.swing.JTextField txtCodigoCadastrarProdutos;
    private javax.swing.JTextField txtNomeCadastrarProdutos;
    private javax.swing.JTextField txtPrecoCadastrarProdutos;
    // End of variables declaration//GEN-END:variables
}
