/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class TalaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TalaCadastro
     */
    public TalaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuarioCadastro = new javax.swing.JTextField();
        lblUsuarioCadastro = new javax.swing.JLabel();
        lblSenhaCadastro = new javax.swing.JLabel();
        txtNomeCadastro = new javax.swing.JTextField();
        lblNomeCadastro = new javax.swing.JLabel();
        txtTelefoneCadastro = new javax.swing.JTextField();
        lblTelefoneCadastro = new javax.swing.JLabel();
        txtEmailCadastro = new javax.swing.JTextField();
        lblEmailCadastro = new javax.swing.JLabel();
        lblCargoCadastro = new javax.swing.JLabel();
        btnSalvarCadastro = new javax.swing.JButton();
        txtSenhaCadastro = new javax.swing.JPasswordField();
        cmbCargoCadastro = new javax.swing.JComboBox<>();
        lblConfimarSenhaCadastro = new javax.swing.JLabel();
        txtConfimarSenhaCadastro = new javax.swing.JPasswordField();
        txtDataDeNascimentoCadastro = new javax.swing.JTextField();
        lblDataDeNascimentoCadastro = new javax.swing.JLabel();
        txtRgCadastro = new javax.swing.JTextField();
        lblRgCadastro = new javax.swing.JLabel();
        txtCpfCadastro = new javax.swing.JTextField();
        lblCpfCadastro = new javax.swing.JLabel();

        setTitle("Cadastro do usuário");
        getContentPane().setLayout(null);
        getContentPane().add(txtUsuarioCadastro);
        txtUsuarioCadastro.setBounds(200, 330, 190, 20);

        lblUsuarioCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarioCadastro.setText("Usuário:");
        getContentPane().add(lblUsuarioCadastro);
        lblUsuarioCadastro.setBounds(20, 330, 70, 20);

        lblSenhaCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenhaCadastro.setText("Senha:");
        getContentPane().add(lblSenhaCadastro);
        lblSenhaCadastro.setBounds(20, 370, 70, 20);

        txtNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeCadastro);
        txtNomeCadastro.setBounds(200, 40, 190, 20);

        lblNomeCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeCadastro.setText("Nome completo:");
        getContentPane().add(lblNomeCadastro);
        lblNomeCadastro.setBounds(20, 40, 140, 20);
        getContentPane().add(txtTelefoneCadastro);
        txtTelefoneCadastro.setBounds(200, 200, 190, 20);

        lblTelefoneCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefoneCadastro.setText("Telefone:");
        getContentPane().add(lblTelefoneCadastro);
        lblTelefoneCadastro.setBounds(20, 200, 80, 20);
        getContentPane().add(txtEmailCadastro);
        txtEmailCadastro.setBounds(200, 240, 190, 20);

        lblEmailCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailCadastro.setText("E-mail:");
        getContentPane().add(lblEmailCadastro);
        lblEmailCadastro.setBounds(20, 240, 80, 20);

        lblCargoCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCargoCadastro.setText("Cargo:");
        getContentPane().add(lblCargoCadastro);
        lblCargoCadastro.setBounds(20, 280, 80, 20);

        btnSalvarCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvarCadastro.setText("Salvar");
        btnSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarCadastro);
        btnSalvarCadastro.setBounds(20, 460, 110, 30);
        getContentPane().add(txtSenhaCadastro);
        txtSenhaCadastro.setBounds(200, 370, 190, 22);

        cmbCargoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Caixa", "Balconista" }));
        getContentPane().add(cmbCargoCadastro);
        cmbCargoCadastro.setBounds(200, 280, 190, 22);

        lblConfimarSenhaCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConfimarSenhaCadastro.setText("Confirmar senha:");
        getContentPane().add(lblConfimarSenhaCadastro);
        lblConfimarSenhaCadastro.setBounds(20, 410, 150, 20);
        getContentPane().add(txtConfimarSenhaCadastro);
        txtConfimarSenhaCadastro.setBounds(200, 410, 190, 22);
        getContentPane().add(txtDataDeNascimentoCadastro);
        txtDataDeNascimentoCadastro.setBounds(200, 80, 190, 20);

        lblDataDeNascimentoCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataDeNascimentoCadastro.setText("Data de Nascimento:");
        getContentPane().add(lblDataDeNascimentoCadastro);
        lblDataDeNascimentoCadastro.setBounds(20, 80, 170, 20);
        getContentPane().add(txtRgCadastro);
        txtRgCadastro.setBounds(200, 120, 190, 20);

        lblRgCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRgCadastro.setText("RG :");
        getContentPane().add(lblRgCadastro);
        lblRgCadastro.setBounds(20, 120, 70, 20);
        getContentPane().add(txtCpfCadastro);
        txtCpfCadastro.setBounds(200, 160, 190, 20);

        lblCpfCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCpfCadastro.setText("CPF:");
        getContentPane().add(lblCpfCadastro);
        lblCpfCadastro.setBounds(20, 160, 70, 20);

        setSize(new java.awt.Dimension(436, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed
        try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/bancopadaria", "root", "Daniel20187480@");
            st = conexao.prepareStatement("INSERT INTO usuario VALUES(?, ?, ?, ?, ?, ?, ?, ?)");
            st.setString(1, txtNomeCadastro.getText());            // 1  2  3  4  5  6  7  8
            st.setString(2, txtDataDeNascimentoCadastro.getText());
            st.setString(3, txtRgCadastro.getText());
            st.setString(4, txtCpfCadastro.getText());
            st.setString(5, txtTelefoneCadastro.getText());
            st.setString(6, txtEmailCadastro.getText());
            st.setString(7, cmbCargoCadastro.getSelectedItem().toString());
            st.setString(8, txtUsuarioCadastro.getText());
            st.setString(9, txtSenhaCadastro.getText());
            
            JOptionPane.showMessageDialog(btnSalvarCadastro, "Dados salvos com sucesso");
            txtUsuarioCadastro.setText("");
            txtSenhaCadastro.setText("");
            txtConfimarSenhaCadastro.setText("");
            txtUsuarioCadastro.requestFocus();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(btnSalvarCadastro, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(btnSalvarCadastro, "Algum parâmetro do BD está incorreto");
        }
    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void txtNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TalaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TalaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TalaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TalaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TalaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarCadastro;
    private javax.swing.JComboBox<String> cmbCargoCadastro;
    private javax.swing.JLabel lblCargoCadastro;
    private javax.swing.JLabel lblConfimarSenhaCadastro;
    private javax.swing.JLabel lblCpfCadastro;
    private javax.swing.JLabel lblDataDeNascimentoCadastro;
    private javax.swing.JLabel lblEmailCadastro;
    private javax.swing.JLabel lblNomeCadastro;
    private javax.swing.JLabel lblRgCadastro;
    private javax.swing.JLabel lblSenhaCadastro;
    private javax.swing.JLabel lblTelefoneCadastro;
    private javax.swing.JLabel lblUsuarioCadastro;
    private javax.swing.JPasswordField txtConfimarSenhaCadastro;
    private javax.swing.JTextField txtCpfCadastro;
    private javax.swing.JTextField txtDataDeNascimentoCadastro;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JTextField txtNomeCadastro;
    private javax.swing.JTextField txtRgCadastro;
    private javax.swing.JPasswordField txtSenhaCadastro;
    private javax.swing.JTextField txtTelefoneCadastro;
    private javax.swing.JTextField txtUsuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
